name: lefthook
version: 0.6.3
author: Igor Kamyshev <igor@kamyshev.me>
description: Fast and powerful Git hooks manager for any type of projects.
homepage: https://github.com/drt-pkgz/lefthook
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  yaml: ^2.1.16
  system_info: ^0.1.1
  archive: ^2.0.10
  cli_util: ^0.1.3+2
executables:
  lefthook: lefthook